/**
 * A subclass that represents a request generated by picking a cell
 * It checks if the play is valid and if the game is over
 *
 * @param game Object of class Game
 * @param pickId Id of picked cell
 */
function RequestValidatePlay(game, pickId) {

  // request type
  var type = "validatePlay";

  // get coordinates of picked cell
  var position = game.playBoard.getPosition(pickId);

  // generate request string
  var requestStr = "validatePlay(something," + game.playBoard.toString() + "," + position[1] + "," + position[0] + ")";

  // super class constructor
  ServerRequest.call(this, type, requestStr);

  // set request onload
  this.request.onload = function(data) {

    var reply = data.target.response;
    console.log("Request: " + type);
    console.log("Server Reply: " + reply);

    if (reply === "yes") {

        // place piece
        game.switchPieceBoard(pickId);

        // check for game over
        new RequestGameCheck(game);
    }
    else {
      console.log("There's already a piece there, please choose a free cell!");
    }
  };

  // set request onerror
  this.request.onerror = function() {
    console.log("Error waiting for response");
  };

  // send request to the server
  this.request.send();
}
RequestValidatePlay.prototype = Object.create(ServerRequest.prototype);
